apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-informer
  namespace: default
  labels:
    app: k8s-informer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-informer
  template:
    metadata:
      labels:
        app: k8s-informer
    spec:
      containers:
      - name: k8s-informer
        image: your-registry/k8s-informer:v1.0  
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-informer-service
  namespace: default
  labels:
    app: k8s-informer
spec:
  type: NodePort
  selector:
    app: k8s-informer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081
      protocol: TCP 