# ai-monitoring-deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-monitoring
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-monitoring-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-monitoring-binding
subjects:
- kind: ServiceAccount
  name: ai-monitoring
  namespace: default
roleRef:
  kind: ClusterRole
  name: ai-monitoring-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-monitoring
  namespace: default
  labels:
    app: ai-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-monitoring
  template:
    metadata:
      labels:
        app: ai-monitoring
    spec:
      serviceAccountName: ai-monitoring 
      containers:
      - name: ai-monitoring
        image: poridhi/ai-monitoring:v1.9
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-monitoring-service
  namespace: default
  labels:
    app: ai-monitoring
spec:
  type: NodePort
  selector:
    app: ai-monitoring
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
